from __future__ import annotations

from app.core.config import settings
from google import genai
from google.genai import types
from pydantic import BaseModel


class LLMResponse(BaseModel):
    """
    Normalized response returned by the language model.

    This model hides provider-specific response objects
    (Gemini, OpenAI, Claude...) from the rest of the
    application.
    """

    text: str


class LLMClient:
    """
    Wrapper around the configured language model.

    Responsibilities
    ----------------
    1. Create the language model client.
    2. Send prompts.
    3. Normalize responses.
    4. Hide provider-specific implementation details.
    """

class LLMError(Exception):
    """Base exception for all LLM-related errors."""


class LLMConnectionError(LLMError):
    """Raised when the language model cannot be reached."""


class LLMResponseError(LLMError):
    """Raised when the language model returns an invalid response."""

    def __init__(self) -> None:
        """
        Initialize the language model client.
        """

        self._client = genai.Client(
            api_key=settings.GEMINI_API_KEY,
        )

        self._model = settings.GEMINI_MODEL

    def generate(
        self,
        prompt: str,
        temperature: float | None = None,
        max_tokens: int | None = None,
    ) -> LLMResponse:
        """
        Send a prompt to the language model.

        Parameters
        ----------
        prompt:
            The complete prompt to send to the model.

        Returns
        -------
        LLMResponse
            The normalized response generated by the model.

        Raises
        ------
        RuntimeError
            If the model fails to generate a valid response.
        """

        try:
            config = types.GenerateContentConfig()

            if temperature is not None:
                config.temperature = temperature

            if max_tokens is not None:
                config.max_output_tokens = max_tokens

            response = self._client.models.generate_content(
                model=self._model,
                contents=prompt,
                config=config,
            )

            text = self._extract_text(response)

            self._validate_response(text)

            return LLMResponse(
                text=text,
            )

        except Exception as exc:
            raise LLMConnectionError(
                "Failed to communicate with the language model."
            ) from exc

    def _extract_text(
        self,
        response: object,
    ) -> str:
        """
        Extract generated text from the provider response.

        This method isolates provider-specific response handling
        from the rest of the application.
        """

        text = getattr(response, "text", None)

        if text is None:
            raise LLMResponseError(
                "Response object does not contain generated text."
            )

        return text.strip()


    def _validate_response(
        self,
        text: str,
    ) -> None:
        """
        Validate the generated response.

        Raises
        ------
        RuntimeError
            If the language model returned an empty response.
        """

        if not text:
            raise LLMResponseError(
                "The language model returned an empty response."
            )

    def test_connection(self) -> bool:
        """
        Verify that the language model is reachable and
        correctly configured.

        Returns
        -------
        bool
            True if the connection succeeds.

        Raises
        ------
        RuntimeError
            If the connection test fails.
        """

        try:
            response = self._client.models.generate_content(
                model=self._model,
                contents="Reply with the word: OK",
            )

            text = self._extract_text(response)

            self._validate_response(text)

            return True

        except Exception as exc:
            raise RuntimeError(
                "Unable to connect to the language model."
            ) from exc

    
